packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  unrs-resolver: false

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - "@turbo/darwin-64@2.10.12"
  - "@turbo/darwin-arm64@2.10.12"
  - "@turbo/linux-64@2.10.12"
  - "@turbo/linux-arm64@2.10.12"
  - "@turbo/windows-64@2.10.12"
  - "@turbo/windows-arm64@2.10.12"
  - "turbo@2.10.12"
